// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApp.DAL.EfDbContext;

namespace TestApp.DAL.Migrations
{
    [DbContext(typeof(TestAppDbContext))]
    [Migration("20220512211154_CorrectOption_UpdateTypeToInt")]
    partial class CorrectOption_UpdateTypeToInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("TestApp.Domains.Domains.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Content = "Karl, a PhD and lecturer at MIT, gave birth to both of his children—and despite being the one with the baby bump, he was routinely asked to wait outside while the nurses attended to his (not pregnant) wife. People were unable, he says, to see both a man and a pregnant body; as a result, Karl became a “fat man” rather than a pregnant person. Despite being assigned female at birth (AFAB) and possessing a uterus and glands for lactating, Karl was not—in the eyes of even the medical staff—the mother. Karl considered himself a PaPa; other transgender parents choose more androgynous terms, largely because of the way motherhood has been construed. At best, says Karl, unconventional pregnant parents cause “total gender confusion” even among medical practitioners, but at worst it results in trauma, violence, and harm, in trans men failing to get emergency care during miscarriages, in trans women being treated as pedophiles, and in nonbinary identities being entirely erased.",
                            CreatedDate = new DateTime(2022, 5, 12, 21, 11, 52, 996, DateTimeKind.Utc).AddTicks(4660),
                            Title = "Science Is Redefining Motherhood. If Only Society Would Let It"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Karl, a PhD and lecturer at MIT, gave birth to both of his children—and despite being the one with the baby bump, he was routinely asked to wait outside while the nurses attended to his (not pregnant) wife. People were unable, he says, to see both a man and a pregnant body; as a result, Karl became a “fat man” rather than a pregnant person. Despite being assigned female at birth (AFAB) and possessing a uterus and glands for lactating, Karl was not—in the eyes of even the medical staff—the mother. Karl considered himself a PaPa; other transgender parents choose more androgynous terms, largely because of the way motherhood has been construed. At best, says Karl, unconventional pregnant parents cause “total gender confusion” even among medical practitioners, but at worst it results in trauma, violence, and harm, in trans men failing to get emergency care during miscarriages, in trans women being treated as pedophiles, and in nonbinary identities being entirely erased.",
                            CreatedDate = new DateTime(2022, 5, 14, 21, 11, 52, 996, DateTimeKind.Utc).AddTicks(9024),
                            Title = "Star Wars Ain’t What It Used to Be"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Karl, a PhD and lecturer at MIT, gave birth to both of his children—and despite being the one with the baby bump, he was routinely asked to wait outside while the nurses attended to his (not pregnant) wife. People were unable, he says, to see both a man and a pregnant body; as a result, Karl became a “fat man” rather than a pregnant person. Despite being assigned female at birth (AFAB) and possessing a uterus and glands for lactating, Karl was not—in the eyes of even the medical staff—the mother. Karl considered himself a PaPa; other transgender parents choose more androgynous terms, largely because of the way motherhood has been construed. At best, says Karl, unconventional pregnant parents cause “total gender confusion” even among medical practitioners, but at worst it results in trauma, violence, and harm, in trans men failing to get emergency care during miscarriages, in trans women being treated as pedophiles, and in nonbinary identities being entirely erased.",
                            CreatedDate = new DateTime(2022, 5, 15, 21, 11, 52, 996, DateTimeKind.Utc).AddTicks(9333),
                            Title = "The Newest iPad Mini Is at Its Lowest Price Ever"
                        },
                        new
                        {
                            Id = 44,
                            Content = "Karl, a PhD and lecturer at MIT, gave birth to both of his children—and despite being the one with the baby bump, he was routinely asked to wait outside while the nurses attended to his (not pregnant) wife. People were unable, he says, to see both a man and a pregnant body; as a result, Karl became a “fat man” rather than a pregnant person. Despite being assigned female at birth (AFAB) and possessing a uterus and glands for lactating, Karl was not—in the eyes of even the medical staff—the mother. Karl considered himself a PaPa; other transgender parents choose more androgynous terms, largely because of the way motherhood has been construed. At best, says Karl, unconventional pregnant parents cause “total gender confusion” even among medical practitioners, but at worst it results in trauma, violence, and harm, in trans men failing to get emergency care during miscarriages, in trans women being treated as pedophiles, and in nonbinary identities being entirely erased.",
                            CreatedDate = new DateTime(2022, 5, 16, 21, 11, 52, 996, DateTimeKind.Utc).AddTicks(9345),
                            Title = "Fast, Cheap, and Out of Control: Inside Shein’s Sudden Rise"
                        },
                        new
                        {
                            Id = 55,
                            Content = "Karl, a PhD and lecturer at MIT, gave birth to both of his children—and despite being the one with the baby bump, he was routinely asked to wait outside while the nurses attended to his (not pregnant) wife. People were unable, he says, to see both a man and a pregnant body; as a result, Karl became a “fat man” rather than a pregnant person. Despite being assigned female at birth (AFAB) and possessing a uterus and glands for lactating, Karl was not—in the eyes of even the medical staff—the mother. Karl considered himself a PaPa; other transgender parents choose more androgynous terms, largely because of the way motherhood has been construed. At best, says Karl, unconventional pregnant parents cause “total gender confusion” even among medical practitioners, but at worst it results in trauma, violence, and harm, in trans men failing to get emergency care during miscarriages, in trans women being treated as pedophiles, and in nonbinary identities being entirely erased.",
                            CreatedDate = new DateTime(2022, 5, 17, 21, 11, 52, 996, DateTimeKind.Utc).AddTicks(9350),
                            Title = "24 Last-Minute Mother’s Day Gifts on Sale Now"
                        });
                });

            modelBuilder.Entity("TestApp.Domains.Domains.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectOption")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inquiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TestApp.Domains.Domains.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestApp.Domains.Domains.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestApp.Domains.Domains.Question", b =>
                {
                    b.HasOne("TestApp.Domains.Domains.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestApp.Domains.Domains.Test", b =>
                {
                    b.HasOne("TestApp.Domains.Domains.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TestApp.Domains.Domains.Test", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
